# -*- coding: utf-8 -*-
"""tc-kimlik-dogrulama

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fb-E-U8ArB0-FckX06-OI5cS6O_45maF
"""

def tc_kimlik(tc):
  if len(tc) != 11:
    return False

  # Check if all characters are digits
  if not tc.isdigit():
    return False

  # First digit cannot be 0
  if int(tc[0]) == 0:
    return False

  # Calculate sums for 10th digit check
  tekler = int(tc[0]) + int(tc[2]) + int(tc[4]) + int(tc[6]) + int(tc[8])
  çiftler = int(tc[1]) + int(tc[3]) + int(tc[5]) + int(tc[7])

  # Check the 10th digit
  if int(tc[9]) != (tekler * 7 - çiftler) % 10:
    return False

  # Check the 11th digit (sum of first 10 digits modulo 10)
  total_first_ten = sum(int(digit) for digit in tc[:10])
  if int(tc[10]) != total_first_ten % 10:
    return False

  return True # All checks passed

tc=input("tc kimliğinizi giriniz:")
if tc_kimlik(tc):
  print("tc doğru")
else:
  print("tc yanlış")